export enum SpreadSheetTypes {
  SELECT_CELL = "SELECT_CELL",
  BUILD_CELLS = "BUILD_CELLS",
  SET_CELLS = "SET_CELLS",
  BUILD_COLUMNS = "BUILD_COLUMNS",
  SET_COLUMNS = "SET_COLUMNS",
  SET_CELL_VALUE = "SET_CELL_VALUE",
  HANDLE_CELL_UPDATE = "HANDLE_CELL_UPDATE",
}
