export enum SpreadSheetTypes {
  SELECT_MULTIPLE_CELLS = "SELECT_MULTIPLE_CELLS",
  BUILD_CELLS = "BUILD_CELLS",
  SET_CELLS = "SET_CELLS",
  SET_MULTIPLE_CELLS = "SET_MULTIPLE_CELLS",
  SET_SELECTED_CELLS = "SET_SELECTED_CELLS",
  BUILD_COLUMNS = "BUILD_COLUMNS",
  SET_COLUMNS = "SET_COLUMNS",
  SET_CELL_VALUE = "SET_CELL_VALUE",
  HANDLE_CELL_UPDATE = "HANDLE_CELL_UPDATE",
  DELETE_MULTIPLE_CELLS_VALUE = "DELETE_MULTIPLE_CELLS_VALUE",
  FETCH_WEATHER = "FETCH_WEATHER",
}
